const mealSuggestions = {
    breakfast: [
      { name: "Idli", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzdOhrXLYDoP0Y8f4CMuUsmqKMtZwwfws6kQ&s" },
      { name: "Poha", image: "https://pipingpotcurry.com/wp-content/uploads/2020/12/Poha-Recipe-indori-Piping-Pot-Curry.jpg" },
      { name: "Paratha", image: "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_1:1/k%2FPhoto%2FRecipe%20Ramp%20Up%2F2022-02-Paratha%2Fparatha-stacked-top_view" },
      { name: "Masala Dosa", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJVrC2Z7OCjmZQ1vrNmWWaJRrMaJ9HzFn2kg&s" },
      { name: "Upma", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR62An25qATwuE83QS6U4uid1_fK5kigq9gMQ&s" },
      { name: "Aloo Puri", image: "https://www.whiskaffair.com/wp-content/uploads/2020/09/Aloo-Puri-2-3.jpg" },
      { name: "Thepla", image: "https://www.sanjanafeasts.co.uk/wp-content/uploads/2020/02/Gujarati-Thepla-Recipe-546x728.jpg.webp" },
      { name: "Dhokla", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhe1ERCasiq33WnyWzqYAAm5exb2sSlGg3mw&s" },
      { name: "Besan Chilla", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQR-w2djr361hsstQCq6E0UzMOc2WNaXl4XpQ&s" },
      { name: "Vegetable Sandwich", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQFiSZ9xUKEitM7VPQbKZIuOHGZXDYTcsxIA&ss" },
    ],
    lunch: [
      { name: "Dal Tadka & Rice", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQm9F8tMZ10JqpkZu3nPBXfICuapzKlc822Dg&s" },
      { name: "Rajma Chawal", image: "https://www.spiceupthecurry.com/wp-content/uploads/2021/03/rajma-chawal-1.jpg" },
      { name: "Vegetable Pulao", image: "https://cdn.zeptonow.com/production///tr:w-600,ar-100-100,pr-true,f-auto,q-80/web/recipes/vegetable-pulao.png" },
      { name: "Paneer Butter Masala", image: "https://www.cookwithmanali.com/wp-content/uploads/2019/05/Paneer-Butter-Masala-500x500.jpg" },
      { name: "Aloo Gobhi with Roti", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgQFB_OBH5lGiJ0MBvOLxaHtFOMVNcwkPuPw&s" },
      { name: "Bhindi Masala with Roti", image: "https://ministryofcurry.com/wp-content/uploads/2020/01/bhindi-masala-1.jpg" },
      { name: "Chana Masala & Rice", image: "https://www.seriouseats.com/thmb/YIZ-JlXSyjZQgSPw4ocvgXn5IM0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/channa-masala-recipe-hero-20685037447b471c8f69f6873087de3a.JPG" },
      { name: "Mixed Vegetable Curry", image: "https://shwetainthekitchen.com/wp-content/uploads/2023/03/mixed-vegetable-curry.jpg" },
      { name: "Palak Paneer with Rice", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOUOHoAo_MoKiOtgJphju_Ona9cVrMjipH4w&s" },
      { name: "Vegetable Biryani", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSjbQoX-2YQZXSoMfT6o1zWy-871kc9YV_dQ&s" },
    ],
    dinner: [
      { name: "Paneer Tikka", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToeBoVqXmwjEjpYEGK1Y1AZi964zw-iK-Vqg&s" },
      { name: "Baingan Bharta & Chapati", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWM3u7sy_w2vdJVaQn6GKygfYBWu3uiAZnYg&s" },
      { name: "Vegetable Khichdi", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7yybC9FL_I7n9Qlf9GFpwE-LIqesFNpJ6uQ&s" },
      { name: "Chole & Bhature", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSHuqEQvNy--dkfLm4j4WW74dgvb2tb4HilQ&s" },
      { name: "Stuffed Capsicum", image: "https://www.vegrecipesofindia.com/wp-content/uploads/2014/06/bharwan-shimla-mirch-recipe.jpg" },
      { name: "Masoor Dal & Rice", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDNPlpmuyobXLk5wfxEiHfki8XWxilUdTXaw&s" },
      { name: "Lauki Kofta & Roti", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReiVebGxDGQz9mvN2FFiROtUMyeK5y3AvhbQ&s" },
      { name: "Aloo Matar with Paratha", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW0IYiigY58rlpUfyXBTAuK5PxaQHj5DIP3Q&s" },
      { name: "Vegetable Stew & Rice", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNq_h1AVYbAADswNmGzcd4_KF_fRf76qqL_Q&s" },
      { name: "Kadhi Pakora with Rice", image: "https://i.pinimg.com/originals/ff/24/00/ff2400744ed2be2bd2b7fcf7a3a26775.jpg" },
    ],
  };
export default mealSuggestions;  