const mealSuggestions = {
    breakfast: [
      { name: "Idli", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzdOhrXLYDoP0Y8f4CMuUsmqKMtZwwfws6kQ&s" },
      { name: "Poha", image: "https://pipingpotcurry.com/wp-content/uploads/2020/12/Poha-Recipe-indori-Piping-Pot-Curry.jpg" },
      { name: "Paratha", image: "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_1:1/k%2FPhoto%2FRecipe%20Ramp%20Up%2F2022-02-Paratha%2Fparatha-stacked-top_view" },
      { name: "Masala Dosa", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJVrC2Z7OCjmZQ1vrNmWWaJRrMaJ9HzFn2kg&s" },
      { name: "Upma", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR62An25qATwuE83QS6U4uid1_fK5kigq9gMQ&s" },
      { name: "Aloo Puri", image: "https://www.whiskaffair.com/wp-content/uploads/2020/09/Aloo-Puri-2-3.jpg" },
      { name: "Thepla", image: "https://www.sanjanafeasts.co.uk/wp-content/uploads/2020/02/Gujarati-Thepla-Recipe-546x728.jpg.webp" },
      { name: "Dhokla", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhe1ERCasiq33WnyWzqYAAm5exb2sSlGg3mw&s" },
      { name: "Besan Chilla", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQR-w2djr361hsstQCq6E0UzMOc2WNaXl4XpQ&s" },
      { name: "Vegetable Sandwich", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQFiSZ9xUKEitM7VPQbKZIuOHGZXDYTcsxIA&ss" },
    ],
    lunch: [
      { name: "Dal Tadka & Rice", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQm9F8tMZ10JqpkZu3nPBXfICuapzKlc822Dg&s" },
      { name: "Rajma Chawal", image: "https://www.spiceupthecurry.com/wp-content/uploads/2021/03/rajma-chawal-1.jpg" },
      { name: "Vegetable Pulao", image: "https://cdn.zeptonow.com/production///tr:w-600,ar-100-100,pr-true,f-auto,q-80/web/recipes/vegetable-pulao.png" },
      { name: "Paneer Butter Masala", image: "https://via.placeholder.com/50" },
      { name: "Aloo Gobhi with Roti", image: "https://via.placeholder.com/50" },
      { name: "Bhindi Masala with Roti", image: "https://via.placeholder.com/50" },
      { name: "Chana Masala & Rice", image: "https://via.placeholder.com/50" },
      { name: "Mixed Vegetable Curry", image: "https://via.placeholder.com/50" },
      { name: "Palak Paneer with Rice", image: "https://via.placeholder.com/50" },
      { name: "Vegetable Biryani", image: "https://via.placeholder.com/50" },
    ],
    dinner: [
      { name: "Paneer Tikka", image: "https://via.placeholder.com/50" },
      { name: "Baingan Bharta & Chapati", image: "https://via.placeholder.com/50" },
      { name: "Vegetable Khichdi", image: "https://via.placeholder.com/50" },
      { name: "Chole & Bhature", image: "https://via.placeholder.com/50" },
      { name: "Stuffed Capsicum", image: "https://via.placeholder.com/50" },
      { name: "Masoor Dal & Rice", image: "https://via.placeholder.com/50" },
      { name: "Lauki Kofta & Roti", image: "https://via.placeholder.com/50" },
      { name: "Aloo Matar with Paratha", image: "https://via.placeholder.com/50" },
      { name: "Vegetable Stew & Rice", image: "https://via.placeholder.com/50" },
      { name: "Kadhi Pakora with Rice", image: "https://via.placeholder.com/50" },
    ],
  };
export default mealSuggestions;  